### ISSUE TITLE
Provide a compiled version for Download through github

### ISSUE THREAD

**Issue by pschrammel** [quantumew/mustache-cli#3]
Hi,

it would be very nice if you could provide a compiled version of this (go is meant for ship dependecyless binaries ... I thought). I think github could even host your downloads.
My use case:
In a Dockerfile I could just do a wget .... > /bin/mustache and have a templating engine for configs (no need for aws/sed fu.. ups).
Thank you very much!

**Comment by quantumew** [comment]
I agree, I sort of threw this tool together. I am really tempted to use something like this https://github.com/goreleaser/goreleaser. Looks very promising. I will get back to you shortly on how I decide to do this. For now I have a few builds under releases which you can retrieve via GitHub's API:

```
endpoint=$(curl "https://api.github.com/repos/quantumew/mustache-cli/releases/latest" | jq -r '.assets[] | .browser_download_url // ""')

curl -L "$endpoint" -o "mustache.tar.gz"
```
If I remember right there is a linux/amd64 and darwin/amd64 there atm. I will expand on this shortly. Thanks!

**Comment by pschrammel** [comment]
damn ...  have overseen your release, thx. this helps me a lot! thx for your fast response.

**Comment by quantumew** [comment]
No problem!
