### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by axos88** [quantumew/mustache-cli#4]
I'd love to use this for my embedded project, but I'd need to fetch the variables from the ENV to generate files during the boot process based on the ramdisk and the non-volatile settings.

Possibly better to add support for .env files, and then `printenv > current.env` can be used to generate this file before invoking.

Is this something that is planned to be added?

**Comment by quantumew** [comment]
It is now! Mentioned on the other issue, but I would probably do something like `mustache template.mustache default.json --override ENV`. Also handle the case where you want env vars as the default `mustache template.mustache ENV --override file.json`. `ENV` again being a special trigger.
