### ISSUE TITLE
Add support for merging multiple variable sources

### ISSUE THREAD

**Issue by axos88** [quantumew/mustache-cli#5]
I'd love to be able to specify multiple sources such as a default set of vars, and a local overriding set of vars, and even the ENV (see #4) as source, like so:

./mustache template.mustache default.json ENV settings.json

default.json:
```
{
  a1: 1
  a2: 2
  a3: 3
}
```

ENV
```
a1 = 5
a2 = 7
```

settings.json
```
{
  "a1" : 42
}
```

The resulting variables should be
```
{
  "a1":42,
  "a2": 7,
  "a3": 3
}
```

**Comment by quantumew** [comment]
I really like this idea. I will try getting to this sometime this week. I will have to think about how this will look. I think it will be close to what you suggested, probably this: `mustache template.mustache default.json --override ENV --override file1.json --override file2.json`. In the code I will respect the order of options, with `ENV` being a special trigger to pull in env vars.

**Comment by quantumew** [comment]
Thanks reporting again, going to have some free time to get this in between tomorrow and Friday.
